### ISSUE TITLE
Xbox no longer detects the A, B, X, and Y button presses

### ISSUE THREAD

**Issue by jaywengrow** [hybridgroup/cylon-joystick#22]
The example at https://github.com/hybridgroup/cylon-joystick/blob/master/examples/xbox360/xbox360.js no longer seems to detect A, B, X, and Y key pressed in the latest release. The last time I had it working was in version 0.8.0, but when I upgraded it no longer works. Thanks!

**Comment by edgarsilva** [comment]
Pretty old issue with no follow up. Closing since we have it working with the new joystick library.
