### ISSUE TITLE
Dualshock-3 detected, no events

### ISSUE THREAD

**Issue by georges6410** [hybridgroup/cylon-joystick#27]
Hello, so I have this bug : my dualshock-3 is ON, connected to my raspi 2, and after launching my code with node, it doesn't get any events.

An hour ago it was working, the buttons, when pressed and release printed a message in console, and event light up a led.

```
var Cylon = require("cylon");

Cylon.robot({
        connections: {
                raspi: {adaptor: "raspi"},
                joystick: {adaptor: "joystick"}
        },
        devices: {
                led: {driver: "led", pin:11, connection: "raspi"},
                controller: {driver: "dualshock-3", connection: "joystick"}
        },
        work: function(my) {
                ["square", "circle", "triangle", "x"].forEach(function(button) {
                        my.controller.on(button + ":down", function() {
                               my.led.turnOn();
                                console.log("button " + button + " pressed");
                        });
                        my.controller.on(button + ":release", function() {
                               my.led.turnOff();
                                console.log("button " + button + " pressed");
                        });

                });
        }
}).start();
```

but, after a deconnection of the controller (it turned off itself because no use), and a reconnection (i turned it on back), no more events.

When I launch "sudo node cylonTest.js" with the controller OFF : 

> 2016-03-13T11:47:22.100Z : [Robot 1] - Starting connections.
> 2016-03-13T11:47:22.133Z : [Robot 1] - Starting connection 'raspi'.
> 2016-03-13T11:47:22.144Z : [Robot 1] - Starting connection 'joystick'.
> 
> Error: No Joysticks available.
>     at Adaptor.connect (/home/georges6410/Documents/PS3_Controller_Projects/controllerForLeds/node_modules/cylon-joystick/lib/adaptor.js:72:11)
>     at Robot.startConnection (/home/georges6410/Documents/PS3_Controller_Projects/controllerForLeds/node_modules/cylon/lib/robot.js:317:22)
>     at Robot.<anonymous> (/home/georges6410/Documents/PS3_Controller_Projects/controllerForLeds/node_modules/cylon/lib/robot.js:288:19)
>     at /home/georges6410/Documents/PS3_Controller_Projects/controllerForLeds/node_modules/cylon/lib/utils/helpers.js:237:36
>     at Array.forEach (native)
>     at Object.parallel (/home/georges6410/Documents/PS3_Controller_Projects/controllerForLeds/node_modules/cylon/lib/utils/helpers.js:237:13)
>     at Robot.startConnections (/home/georges6410/Documents/PS3_Controller_Projects/controllerForLeds/node_modules/cylon/lib/robot.js:292:12)
>     at next (/home/georges6410/Documents/PS3_Controller_Projects/controllerForLeds/node_modules/cylon/lib/utils/helpers.js:266:22)
>     at Object.series (/home/georges6410/Documents/PS3_Controller_Projects/controllerForLeds/node_modules/cylon/lib/utils/helpers.js:270:3)
>     at Robot.start (/home/georges6410/Documents/PS3_Controller_Projects/controllerForLeds/node_modules/cylon/lib/robot.js:235:5)

And when I turn the controller on, and launch "sudo node cylonTest.js" : 

> 2016-03-13T11:48:51.658Z : [Robot 1] - Starting connections.
> 2016-03-13T11:48:51.687Z : [Robot 1] - Starting connection 'raspi'.
> 2016-03-13T11:48:51.695Z : [Robot 1] - Starting connection 'joystick'.
> 2016-03-13T11:48:51.852Z : [Robot 1] - Starting devices.
> 2016-03-13T11:48:51.853Z : [Robot 1] - Starting device 'led' on pin 11.
> 2016-03-13T11:48:51.854Z : [Robot 1] - Starting device 'controller'.
> 2016-03-13T11:48:51.857Z : [Robot 1] - Working.

But when I press the buttons : no events and no console.log

Is there anyone who could help me with this problem ?

Thanks.

**Comment by deadprogram** [comment]
Hi, @georges6410 as I recall you need to turn on the DS3 by pushing both the "PS" & "Select" buttons at the same time until it light up, then plug the USB cable in.

Hope that helps!

**Comment by georges6410** [comment]
I'll try this in a few minutes, but why does I have to plug the USB ? Didn't mention it but I use a bluetooth dongle.

The whole configuration was the same between the moment it worked (events caught) and the moment it didn't work anymore (not a single event caught), 30 minutes later.

I'll come back after the test.

**Comment by georges6410** [comment]
I'll try this in a few minutes, but why does I have to plug the USB ? Didn't mention it but I use a bluetooth dongle.

The whole configuration was the same between the moment it worked (events caught) and the moment it didn't work anymore (not a single event caught), 30 minutes later.

I'll come back after the test.

Edit : i've turned on the DS3 controller via HOME + SELECT until the P1 led stayed fix.
I've launched "sudo node cylonTest.js" and still no event caught.

**Comment by deadprogram** [comment]
I use my controller in a plugged in mode, myself. Did not realize you were using it in a wireless mode.

What OS and Node version are you running?

From the sound of it, is probably something to do with your Bluetooth configuration, and not Cylon.js itself per se. You might want to remove the controller from the list of devices, and pair/connect again.

**Comment by georges6410** [comment]
I've already tried to remove my controller from my authorized devices and added it again.

I run : Linux raspberrypi 4.1.18-v7+ #846 SMP Thu Feb 25 14:22:53 GMT 2016 armv7l GNU/Linux
Node : v0.10.29

**Comment by deadprogram** [comment]
Are you using bluez 4 or 5? Also, are you using the Bluetooth GUI to connect, or CLI?

**Comment by georges6410** [comment]
When i use this dpkg --status bluez | grep '^Version:', I get : 
Version: 5.23-2+rpi1

I've used the CLI (with sudo bluetoothctl and connect MAC ; trust MAC...)

**Comment by deadprogram** [comment]
I use a similar setup, but with a DS4. In my case, I run screen to get another session for bluetoothctl, do you do that as well?

Within bluetoothctl I run the following sequence:

```
agent on
default-agent
connect MAC
```

**Comment by georges6410** [comment]
Okay, so I've tried with the wire : it works.
So, steps : 

1) connect the USB to the controller then to the Raspi2 ; the LEDs blink
2) launch sudo bluetoothctl ; agent on ; default-agent ; connect MAC
3) Shortly press "PS" button ; the P1 LED stay fixed, others are off
4) launch sudo node cylonTest.js
5) press buttons : events caught

If I try the same but without wire : 

1) turn on the controller then to the Raspi2 ; the LEDs blink ; after a few seconds the P1 LED stay fixed, others are off
2) launch sudo bluetoothctl ; agent on ; default-agent ; connect MAC
3) Shortly press "PS" button
4) launch sudo node cylonTest.js
5) press buttons : events not caught

So I think I'll be using the wire. But it kinda annoys me that wireless was working, and 30 minutes later : no.

**Comment by deadprogram** [comment]
Remember you need to leave the `bluetoothctl` running in another session, if you exit it closes the connection. That is why I use `screen`

**Comment by georges6410** [comment]
Yep, I left a terminal with `bluetoothctl`.

What is `screen` ?

**Comment by deadprogram** [comment]
http://linux.die.net/man/1/screen but you are doing the same thing by running multiple terminal under the GUI. I run headless and SSH in, usually.

**Comment by georges6410** [comment]
Okay, thanks.

I change this issue to "Solved", if, later, I find how it can work without wire, I'll put it here.

Thanks a lot !

**Comment by tiferrei** [comment]
Hey guys, I'm trying to connect my DS4 via bluetooth, but I also get no output when I press the buttons, all I get is this:

```
2016-09-15T21:28:36.473Z : [Robot 1] - Starting connections.
2016-09-15T21:28:36.479Z : [Robot 1] - Starting connection 'joystick'.
2016-09-15T21:28:36.489Z : [Robot 1] - Starting devices.
2016-09-15T21:28:36.489Z : [Robot 1] - Starting device 'controller'.

2016-09-15T21:28:36.490Z : [Robot 1] - Working.
```

Here's my code:

```
var Cylon = require('cylon');

Cylon.robot({
  connections: {
    joystick: { adaptor: 'joystick' }
  },

  devices: {
    controller: { driver: 'dualshock-3', connection: "joystick" }
  },

work: function(my) {
    ["square", "circle", "x", "triangle"].forEach(function(button) {
      my.controller.on(button + ":press", function() {
        console.log("Button " + button + " pressed.");
      });

      my.controller.on(button + ":release", function() {
        console.log("Button " + button + " released.");
      });
    });

    my.controller.on("left_x:move", function(pos) {
      console.log("Left Stick - X:", pos);
    });

    my.controller.on("right_x:move", function(pos) {
      console.log("Right Stick - X:", pos);
    });

    my.controller.on("left_y:move", function(pos) {
      console.log("Left Stick - Y:", pos);
    });

    my.controller.on("right_y:move", function(pos) {
      console.log("Right Stick - Y:", pos);
    });
  }
}).start();
```

What am I doing wrong?

Thanks

**Comment by deadprogram** [comment]
For one thing if you are using a ds4 your code should have:

``` javascript
 controller: { driver: 'dualshock-4', connection: "joystick" }
```

**Comment by tiferrei** [comment]
Tried that but still nothing :/

**Comment by tiferrei** [comment]
I wonder, how does it know which bluetooth device to connect to? Most frameworks require me to give the UDID

**Comment by deadprogram** [comment]
It uses sdl and connects to the first joystick with a matching name.

Question: did you connect to the ds4 using bluetoothctrl or  something else?

**Comment by tiferrei** [comment]
On macOS so no, directly through the system preferences.

**Comment by deadprogram** [comment]
I've used only used ds3 on osx, and that was using a usb cable. I'd check to make sure it is connected in os first, if possible.

**Comment by tiferrei** [comment]
In the system report it says it is connected, also the light on the controller is solid so I assume it's also connected.

**Comment by deadprogram** [comment]
And is it a 'real' controller or a clone?

**Comment by tiferrei** [comment]
Real, I believe it's real, it's the one that came with the PlayStation, sorry I'm more into programming than gaming :P

**Comment by deadprogram** [comment]
That's a real one, then. And your version of node and osx are?

**Comment by tiferrei** [comment]
macOS Sierra 10.12 GM
node 6.5.0

**Comment by tiferrei** [comment]
Hey @deadprogram, any progress on this?
BTW, I installed the SDL framework on my Mac (`Library/Frameworks`) to see if that would make something but still nothing :/

**Comment by tiferrei** [comment]
Any progress on this @deadprogram?
